version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # web: TODO
  api:
    build: ./api
    command: hypercorn api.main:app -b 0.0.0.0:3000 --reload
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    environment:
      DB_URL: postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
