version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: ghcr.io/monochromecms/monochrome-api-postgres:v1.2.2
    command: hypercorn api.main:app -b 0.0.0.0:3000 --root-path /api
    volumes:
      - ./media:/media
    environment:
      DB_URL: postgresql+asyncpg://${DB_USER}:${DB_PWD}@db:5432/${DB_NAME}
      JWT_SECRET_KEY: ${SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      CORS_ORIGINS: ${PROTOCOL}://${DOMAIN_NAME}
    depends_on:
      - db
  web:
    build:
      target: caddy
      context: ./monochrome-webui
      args:
        VUE_APP_DOMAIN_NAME: ${DOMAIN_NAME}
        VUE_APP_TITLE: ${TITLE}
        VUE_APP_DESCRIPTION: ${DESCRIPTION}
        VUE_APP_PROTOCOL: ${PROTOCOL}
        VUE_APP_SECRET: ${SESSION_SECRET_KEY}
        VUE_APP_MEDIA_PATH: ${PROTOCOL}://${DOMAIN_NAME}/media
        VUE_APP_API_PATH: ${PROTOCOL}://${DOMAIN_NAME}/api
    volumes:
    - ./media:/srv/media
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PROTOCOL: ${PROTOCOL}
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  caddy_data:
  caddy_config: