version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/monochromecms/monochrome-api:latest
    volumes:
      - ./media:/media
    environment:
      MEDIA_BACKEND: FS
      MEDIA_PATH: "/media"
      ROOT_PATH: "/api"
      DB_BACKEND: POSTGRES
      PG_USER: ${DB_USER}
      PG_PASS: ${DB_PWD}
      PG_DB: ${DB_NAME}
      PG_HOST: db:5432
      JWT_SECRET_KEY: ${SECRET_KEY}
      JWT_COOKIE_SAMESITE: strict
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
    depends_on:
      db:
        condition: service_healthy

  web:
    image: monochrome-webui-caddy
    build:
      target: caddy
      context: ./monochrome-webui
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        TITLE: ${TITLE}
        DESCRIPTION: ${DESCRIPTION}
        PROTOCOL: ${PROTOCOL}
        VITE_MEDIA_PATH: /media
        VITE_API_PATH: /api
    volumes:
      - ./media:/srv/media
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PROTOCOL: ${PROTOCOL}
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
