version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
  api:
    image: monochrome-api
    build: ./api
    command: python -m pytest --cov api --cov-report html:/api/htmlcov --cov-config=/api/setup.cfg -v api
    volumes:
      - ./api:/api
      - ./media_test:/media
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: testKey
      MEDIA_PATH: /media
    depends_on:
      - db

