version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: ./api
    command: hypercorn api.main:app -b 0.0.0.0:3000 --reload --root-path /api
    volumes:
      - ./api:/api
      - ./media:/media
    environment:
      DB_URL: postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MEDIA_PATH: /media
    depends_on:
      - db
  web-dev:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
    - ./web:/app

  caddy:
    image: caddy:2-alpine
    volumes:
      - caddy_data:/data
      - ./media:/media
      - ./web/Caddyfile.dev:/etc/caddy/Caddyfile
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - 80:80

volumes:
  postgres_data:
  caddy_data:
