version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: ghcr.io/monochromecms/monochrome-api:latest
    volumes:
      - ./media:/media
    environment:
      MEDIA_BACKEND: FS
      MEDIA_PATH: "/media"
      DB_BACKEND: POSTGRES
      PG_USER: ${DB_USER}
      PG_PASS: ${DB_PWD}
      PG_DB: ${DB_NAME}
      PG_HOST: db:5432
      JWT_SECRET_KEY: ${SECRET_KEY}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
    depends_on:
      - db
  web:
    image: monochrome-webui-caddy
    build:
      target: caddy
      context: ./monochrome-webui
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        TITLE: ${TITLE}
        DESCRIPTION: ${DESCRIPTION}
        PROTOCOL: ${PROTOCOL}
        VUE_APP_SECRET: ${SESSION_SECRET_KEY}
        VUE_APP_MEDIA_PATH: /media
        VUE_APP_API_PATH: /api
        VUE_APP_I18N_LOCALES: ${LANGS}
        VUE_APP_I18N_LOCALE: ${DEFAULT_LANG}
    volumes:
    - ./media:/srv/media
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PROTOCOL: ${PROTOCOL}
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
